language: ruby
rvm:
  - 2.6
sudo: false
script: bundle exec jekyll build && bundle exec rake deploy 
addons:
  apt:
    packages:
      - graphviz 
env:
  global:
    secure: ${{secrets.DEPLOY_KEY}}
before_install:
  - yes | gem update --system --force
  - gem install bundler