language: ruby
rvm:
  - 2.6
sudo: false
script: bundle exec jekyll build && bundle exec rake deploy 
addons:
  apt:
    packages:
      - graphviz 
env:
  global:
    secure: ${DEPLOY-KEY}
before_install:
   - gem install bundler