remote_theme: pmarsceill/just-the-docs
theme: "just-the-docs"

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Requirements templates
description: Шаблоны требований для системных аналитиков
# baseurl: "/requirements-templates" # the subpath of your site, e.g. /blog
# url: "https://katerina-glushko.github.io" # the base hostname & protocol for your site, e.g. http://example.com

#permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.adoc

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/just-the-docs.png"

# Enable or disable the site search
search_enabled: true

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Requirements templates on GitHub":
    - "//github.com/katerina-glushko/requirements-templates"

# Footer content appears at the bottom of every page's main content
#footer_content: ""

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
#ga_tracking: 

plugins:
  - jekyll-seo-tag
  - asciidoctor-diagram
  - jekyll-asciidoc

whitelist:
  - jekyll-asciidoc
  - asciidoctor-diagram

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

keep_files:
  - /images
  - images
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - imagesdir=/images
