@startuml

title {desc}
start
repeat
    :получить сообщение из очереди;
    if (тип = ...?) then (yes)
        :найти запись в БД\n**таблица**: objects;
        :обновить статус записи в БД;
    else (no)
        :...;
    endif
repeat while (все сообщения обработаны?)
stop

@enduml