@startuml
left to right direction
skinparam legendBackgroundColor white
allow_mixing
hide empty methods
hide empty attributes
hide circle
set namespaceSeparator //

!$urlbase=''
!unquoted function object($name, $alt_name='', $desc='', $subdesc='', $show_code=0, $add_url=1)
    !if (($add_url==1) && ($urlbase!='') && (%strpos($name,' ')<0))
        !$showname = $urlbase + $name + $urlend + ' ' + $name + ']]'
    !else
        !$showname = $name
    !endif
    !if ($alt_name=='')
        !$res = 'class '+ $name + ' as "<size:16>**' + $showname + '**</size>'
    !else
        !if ($show_code==1)
            !$res = 'class '+ $alt_name + ' as "<size:16>**' + $showname + '**</size>' + '\n<size:12><color:dimgrey>' + $alt_name
        !else
            !$res = 'class '+ $alt_name + ' as "<size:16>**' + $showname + '**</size>'
        !endif
    !endif
    !if ($desc!='')
        !$res = $res+ '\n<size:10>'+$desc
        !if ($subdesc!='')
            !$res = $res+ '\n<size:10>'+$subdesc
        !endif
    !endif
    !$res=$res+'"'
    !return $res
!endfunction
!unquoted function field($name, $desc='', $is_primary=0, $is_foreign=0)
    !$res = '<size:12>' + $name + '</size>'
    !if ($is_primary==1)
        !$res = '<&key> <color:green>' + $res
    !else
        !if ($is_foreign==1)
            !$res = '<&link-intact> <color:blue>' + $res
        !else
            !$res = '<size:12>   ' + $name + '</size>'
        !endif
    !endif
    !if ($desc!='')
        !$res = $res+ '<color:black> - <i>'+$desc
    !endif
    !return $res
!endfunction
hide methods
hide stereotypes


!$legend_show=0
!if ($legend_show==1)
legend right
   |= arrow |= desc|
   | <img:https://github.com/katerina-glushko/requirements-templates/raw/master/templates/diagrams/exactly-one-arrow.png>| Zero or One |
   | <img:https://github.com/katerina-glushko/requirements-templates/raw/master/templates/diagrams/zero-or-one-arrow.png> | Exactly One |
   | <img:https://github.com/katerina-glushko/requirements-templates/raw/master/templates/diagrams/zero-or-many-arrow.png> | Zero or Many |
   | <img:https://github.com/katerina-glushko/requirements-templates/raw/master/templates/diagrams/one-or-many-arrow.png> | One or Many |
endlegend
!endif
@enduml
