@startuml
left to right direction
allow_mixing
hide empty methods
hide empty attributes
hide circle
set namespaceSeparator //

!unquoted function object($name, $alt_name='', $desc='', $subdesc='')
    !if ($aer_name!='')
        !$res = 'class '+ $alt_name + ' as "<size:16>**' + $name + '**</size>' + '\n<size:12><color:dimgrey>' + $alt_name
    !else
        !$res = 'class '+ $name + ' as "<size:16>**' + $name + '**</size>'
    !endif
    !if ($desc!='')
        !$res = $res+ '\n<size:10>'+$desc
        !if ($subdesc!='')
            !$res = $res+ '\n<size:10>'+$subdesc
        !endif
    !endif
    !$res=$res+'"'
    !return $res
!endfunction
!unquoted function field($name, $desc='', $is_primary=0, $is_foreign=0)
    !$res = '<size:12>' + $name + '</size>'
    !if ($is_primary==1)
        !$res = '<&key> <color:green>' + $res
    !else
        !if ($is_foreign==1)
            !$res = '<&link-intact> <color:blue>' + $res
        !else
            !$res = '<size:12>   ' + $name + '</size>'
        !endif
    !endif
    !if ($desc!='')
        !$res = $res+ '<color:black> - <i>'+$desc
    !endif
    !return $res
!endfunction
hide methods
hide stereotypes


legend
   |= arrow |= desc|
   | <img:http://www.plantuml.com/plantuml/png/VOvBJWH1243tTGekC0jlCBQ95_04J1NJHOQ23j3fj9-xgz55HurBtYCFpf7ekGufGjU4D72UUq9ZfvfiMkB6kg3ZW0lMs-osQdimCOTqrFXGf7dO4bRAVI5OJFRFeNHk13IMt65GTcjnH9ZfV5cJlcbbhqA7O1MCU3JDhwjRv_nJF_4pmTrF0ozb-kVloRoH_-PlXqvqRBQnpd152IhtS3hPAqpbJDhM8Uy0> | Zero or \n One |
   | <img:http://www.plantuml.com/plantuml/png/VOvHJWD1243_vnHSe1_UeAw95_04T8Rka3Am0JRDQhsx6ltOgEadxv47nqZqN8SKeND26ZZFFQ6nKqqsBN5XNT1nm0dhPNPRjJsPc4CwQdmgqjnj2IlbjX0i9jlNK3et0XfBRZ0ekxNO8ynqFgr9FxIoLw5Ti0f6F9lczzLhv_nNl_0hmSDl0szbklFtPDx8__BtNISwDhkopd162IgFS3ZSRZ2L8sbRXtm0> | Exactly \n One |
   | <img:http://www.plantuml.com/plantuml/png/VOvHJiH0243_vnHSO3-ymLeJB-09s1csGvQ11cWsjV7kQlIZKUCdxv47vqZqN8SKeMj26ZZFFQ6nKqqsBN5ZNT1nm0NhRNPRjJsPc4CwQdmeqZni2IlbjX0i9jldK3et0XfBRZ0ekxKu8inqlgn9txIoLw53i0f6F9lcrzLxv_nJl_0hmSDF0tkP_lbxCc_al_dReHCTczrPPxYY19L7E9riXwcSITiwv1q0> | Zero or \n Many |
   | <img:http://www.plantuml.com/plantuml/png/VOvHJWD1243_vnHSe1_UeAw95_04T8Rka3Am0JRDMhsx6ltOgEadxv47nqZqN8SKeND26ZZFFQ6nKqqsBN5XNT1nm0dhPNPRjJsPc4CwQdmgqjnj2IlbjX0i9jlNK3et0XfBRZ0ekxNO8ynqFgr9FxIoLw5Ti0f6F9lczzLhv_nNl_0hmSDl0xSotVbxCc_aV_dxhXCTcrrPPpYZ19L7E1pURZ2L8sbRXtm0> | One or \n Many |
endlegend
@enduml
