:page-title: Service specification
:page-parent: Templates
:page-nav_order: 2
:page-has_children: true
:doctype: book

// :page-permalink: /templates/service-specification
NOTE: Данный формат спецификации предполагает ведение документации рядом с кодом.

= Спецификация на сервис 

[cols="1h,2d"]
|===

|Этап
|В процессе разработки сервиса

|Описание
|Подробное описание функций и параметров сервиса

|Автор
a|
* [*] Системный аналитик

|Цель
a|
Постанока задачи на доработку, чтобы

* [*] Разработчик понимал все детали требуемой доработки

Сопроводительное описание сервиса, поддерживаемое в актуальном состоянии, чтобы

* [*] Support использовал в случае разбора инцидента или необходимости изменить конфигурацию
* [*] Системные аналитики разбирались в возможностях сервиса на случай использования или необходимости доработки

|Целевая аудитория
a|
* [*] Системные администраторы (Support)
* [*] Системные аналитики
* [*] Разработка

|===

== Структура

[plantuml, format=png, opts="inline"]
----
@startsalt
{
{T
+ Название сервиса
++ API метод 1
+++ Алгоритм
+++ Запрос
++++ Пример
++++ Параметры
+++ Ответ
++++ Пример
++++ Параметры
+++ Ошибки
++ ...
++ API метод N
+++ ...
++ Процедура (по расписанию/по событию)
+++ Алгоритм
+++ Форматы данных
++ Хранилище
+++ Таблица/Коллекция
++++ Пример
++++ Параметры
++ Конфигурация
+++ Параметры
}
}
@endsalt
----