:page-title: Service specification
:page-parent: Templates
:page-nav_order: 2
:page-has_children: true
:doctype: book

// :page-permalink: /templates/service-specification
NOTE: Данный формат спецификации предполагает ведение документации рядом с кодом.

= Спецификация на сервис 

[cols="1h,2d"]
|===

|Этап
|В процессе разработки сервиса

|Описание
|Подробное описание функций и параметров сервиса

|Цель
a|
Постанока задачи на доработку, чтобы

* [*] Разработчик понимал все детали требуемой доработки

Сопроводительное описание сервиса, поддерживаемое в актуальном состоянии, чтобы

* [*] Support использовал в случае разбора инцидента или необходимости изменить конфигурацию
* [*] Системные аналитики разбирались в возможностях сервиса на случай использования или необходимости доработки

|Целевая аудитория
a|
* [*] Системные администраторы (Support)
* [*] Системные аналитики
* [*] Разработка

|===

== Структура

[plantuml, format=png, opts="inline"]
----
skinparam Legend{
    FontSize 17
}

legend
Service name
|_ API метод
  |_ Алгоритм
  |_ Запрос
  |_ Ответ
  |_ Ошибки
|_ Процедура (по расписанию/по событию)
  |_ Алгоритм
  |_ Форматы данных
|_ Конфигурация
  |_ Параметры
end legend
----